name: integration tests

on:
  push:
    branches:
      - main
    paths:
      - .pre-commit-config.yaml
      - .github/workflows/code_checks.yml
      - .github/workflows/docs_build.yml
      - .github/workflows/docs_deploy.yml
      - .github/workflows/integration_tests.yml
      - '**.py'
      - '**.ipynb'
      - '**.html'
      - '**.js'
      - uv.lock
      - pyproject.toml
      - '**.rst'
      - '**.md'
  pull_request:
    branches:
      - main
    paths:
      - .pre-commit-config.yaml
      - .github/workflows/code_checks.yml
      - .github/workflows/docs_build.yml
      - .github/workflows/docs_deploy.yml
      - .github/workflows/integration_tests.yml
      - '**.py'
      - '**.ipynb'
      - uv.lock
      - pyproject.toml
      - '**.rst'
      - '**.md'

jobs:
  integration-tests:
    runs-on: [self-hosted, db]
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: 'true'
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.5.21"
          enable-cache: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install dependencies and check code
        run: |
          uv sync --dev
          coverage run -m pytest -m integration_test && coverage xml && coverage report -m
      - name: Upload coverage to Codecov
        uses: Wandalen/wretry.action@v3.8.0
        with:
          action: codecov/codecov-action@v4.0.0
          with: |
            token: ${{ secrets.CODECOV_TOKEN }}
            file: ./coverage.xml
            name: codecov-umbrella
            fail_ci_if_error: true
          attempt_limit: 5
          attempt_delay: 30000
