name: publish package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev libssl-dev
      - uses: actions/checkout@v4.2.2
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.21"
          enable-cache: true
      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version-file: ".python-version"
      - name: Install the project
        run: |
          uv sync --all-extras --dev
          source .venv/bin/activate
      - name: Build package
        run: uv build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
